name: Terraform Lint and Validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform-lint-validate:
    name: Lint and Validate Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest  # You can specify a version like "1.5.5"

      - name: Initialize Terraform
        run: terraform init

      - name: Check Terraform Formatting
        run: terraform fmt -check -diff

      - name: Validate Terraform Configuration
        run: terraform validate
